### ISSUE TITLE
Can't run evaluation

### ISSUE THREAD

**Issue by asimniazi63** [Reza-esfandiarpoor/pseudo-shots#1]
tcmalloc: large alloc 1917034496 bytes == 0x55eea4e02000 @  0x7f71019e61e7 0x7f70a562946e 0x7f70a567de7c 0x7f70a567eaaf 0x7f70a5720470 0x55ee8e2a5d54 0x55ee8e2a5a50 0x55ee8e31a105 0x55ee8e3144ae 0x55ee8e2a73ea 0x55ee8e31632a 0x55ee8e3144ae 0x55ee8e2a73ea 0x55ee8e3197f0 0x55ee8e3147ad 0x55ee8e2a7c9f 0x55ee8e2e8d79 0x55ee8e2e5cc4 0x55ee8e2a7ea1 0x55ee8e316bb5 0x55ee8e2a730a 0x55ee8e3153b5 0x55ee8e3144ae 0x55ee8e3141b3 0x55ee8e3de182 0x55ee8e3de4fd 0x55ee8e3de3a6 0x55ee8e3b5723 0x55ee8e3b53cc 0x7f71007d0bf7 0x55ee8e3b52aa
test dataset with top 3 similar classes and auxiliary data level: 0
eval: 1:   0% 0/200 [00:00<?, ?it/s]Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 990, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/lib/python3.7/queue.py", line 179, in get
    self.not_empty.wait(remaining)
  File "/usr/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 418) exited unexpectedly with exit code 1. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test_few_shot.py", line 130, in <module>
    main(config)
  File "test_few_shot.py", line 64, in main
    for data in tqdm(loader, desc=f"eval: {epoch}", leave=False):
  File "/usr/local/lib/python3.7/dist-packages/tqdm/std.py", line 1104, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1186, in _next_data
    idx, data = self._get_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1142, in _get_data
    success, data = self._try_get_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1003, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 418) exited unexpectedly

**Comment by Reza-esfandiarpoor** [comment]
It looks like you are running out of memory. If you set the number of workers in the dataloader to zero, it will return a more informative traceback.

EDIT: the number of workers should be zero to get a nice traceback.

**Comment by huangjin520** [comment]
> It looks like you are running out of memory. If you set the number of workers in the dataloader to one, it will return a more informative traceback.

I encounter the same question. Now i change the num_threads =1, but it still can't work ,raising the same infomation.

**Comment by Reza-esfandiarpoor** [comment]
> > It looks like you are running out of memory. If you set the number of workers in the dataloader to one, it will return a more informative traceback.
> 
> I encounter the same question. Now i change the num_threads =1, but it still can't work ,raising the same infomation.

We've updated the code and the paper. You can find the updated version of the paper and its code here: https://github.com/BatsResearch/efsl
Please open an issue in the new repo if you get errors with the new code!

**Comment by Reza-esfandiarpoor** [comment]
Please see this repo for the new code: https://github.com/BatsResearch/efsl
